version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - deploy:
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    git config --global user.email "me+bot@fangyi.io";
                    git config --global user.name "Fangyi Zhou (bot)";
                    yarn deploy
                  fi

workflows:
  version: 2
  build:
    jobs:
      - build
